AWSTemplateFormatVersion: '2010-09-09'

Description: CloudShrink central account stack
Parameters:
  StackName:
    Type: String
    Default: cloudshrink
  FrontendDomainName:
    Type: String
    Default: ''
  ArtifactsBucket:
    Type: String
    Description: S3 bucket for deployment artifacts
  ApiHandlerKey:
    Type: String
    Description: S3 key for API handler
  DiscoveryWorkerKey:
    Type: String
    Description: S3 key for Discovery worker
  EvaluationWorkerKey:
    Type: String
    Description: S3 key for Evaluation worker
  StepTriggerKey:
    Type: String
    Description: S3 key for Step Trigger
  StateMachineKey:
    Type: String
    Description: S3 key for State Machine definition

Resources:
  AccountsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${StackName}-Accounts"
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: accountId
          AttributeType: S
      KeySchema:
        - AttributeName: accountId
          KeyType: HASH
  PoliciesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${StackName}-Policies"
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
  VolumesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${StackName}-Volumes"
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: volumeId
          AttributeType: S
      KeySchema:
        - AttributeName: volumeId
          KeyType: HASH
  OperationsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${StackName}-Operations"
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Sub "${StackName}-users"
      AutoVerifiedAttributes: [email]
      UsernameAttributes: [email]
  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: web
      UserPoolId: !Ref UserPool
      GenerateSecret: false
      ExplicitAuthFlows:
        - ADMIN_NO_SRP_AUTH
      SupportedIdentityProviders: [COGNITO]
  FrontendBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${AWS::AccountId}-${StackName}-frontend"
      WebsiteConfiguration:
        IndexDocument: index.html
  FrontendBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref FrontendBucket
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal: '*'
            Action: s3:GetObject
            Resource: !Sub "${FrontendBucket.Arn}/*"
  CloudFrontOAI:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        DefaultRootObject: index.html
        Origins:
          - DomainName: !GetAtt FrontendBucket.RegionalDomainName
            Id: s3origin
            S3OriginConfig:
              OriginAccessIdentity: !Sub "origin-access-identity/cloudfront/${CloudFrontOAI}" 
        DefaultCacheBehavior:
          AllowedMethods: [GET, HEAD, OPTIONS]
          CachedMethods: [GET, HEAD]
          TargetOriginId: s3origin
          ViewerProtocolPolicy: redirect-to-https
          ForwardedValues:
            QueryString: true
        PriceClass: PriceClass_100
  ApiFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: ApiDynamoDBAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:GetItem
                  - dynamodb:PutItem
                  - dynamodb:UpdateItem
                  - dynamodb:DeleteItem
                  - dynamodb:Query
                  - dynamodb:Scan
                  - dynamodb:BatchGetItem
                  - dynamodb:BatchWriteItem
                Resource:
                  - !GetAtt AccountsTable.Arn
                  - !GetAtt PoliciesTable.Arn
                  - !GetAtt VolumesTable.Arn
                  - !GetAtt OperationsTable.Arn
  ApiFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub "${StackName}-api"
      Runtime: python3.12
      Handler: app.lambda_handler
      Role: !GetAtt ApiFunctionRole.Arn
      Code:
        S3Bucket: !Ref ArtifactsBucket
        S3Key: !Ref ApiHandlerKey
      Timeout: 30
      Environment:
        Variables:
          ACCOUNTS_TABLE: !Ref AccountsTable
          POLICIES_TABLE: !Ref PoliciesTable
          VOLUMES_TABLE: !Ref VolumesTable
          OPERATIONS_TABLE: !Ref OperationsTable
  ApiGateway:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: !Sub "${StackName}-api"
      ProtocolType: HTTP
  ApiIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref ApiGateway
      IntegrationType: AWS_PROXY
      IntegrationUri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ApiFunction.Arn}/invocations
  ApiRouteAccountsGet:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref ApiGateway
      RouteKey: 'GET /accounts'
      Target: !Sub integrations/${ApiIntegration}
  ApiRouteAccountsPost:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref ApiGateway
      RouteKey: 'POST /accounts'
      Target: !Sub integrations/${ApiIntegration}
  ApiRoutePoliciesGet:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref ApiGateway
      RouteKey: 'GET /policies'
      Target: !Sub integrations/${ApiIntegration}
  ApiRoutePoliciesPost:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref ApiGateway
      RouteKey: 'POST /policies'
      Target: !Sub integrations/${ApiIntegration}
  ApiRouteVolumesGet:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref ApiGateway
      RouteKey: 'GET /volumes'
      Target: !Sub integrations/${ApiIntegration}
  ApiRouteOperationsPost:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref ApiGateway
      RouteKey: 'POST /operations'
      Target: !Sub integrations/${ApiIntegration}
  ApiRouteOperationsGet:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref ApiGateway
      RouteKey: 'GET /operations/{id}'
      Target: !Sub integrations/${ApiIntegration}
  ApiRouteScanPost:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref ApiGateway
      RouteKey: 'POST /scan'
      Target: !Sub integrations/${ApiIntegration}
  ApiStage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      ApiId: !Ref ApiGateway
      StageName: $default
      AutoDeploy: true
  ApiInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref ApiFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ApiGateway}/*/*
  DiscoveryFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: DiscoveryPolicies
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:GetItem
                  - dynamodb:PutItem
                  - dynamodb:UpdateItem
                  - dynamodb:DeleteItem
                  - dynamodb:Query
                  - dynamodb:Scan
                  - dynamodb:BatchGetItem
                  - dynamodb:BatchWriteItem
                Resource: !GetAtt VolumesTable.Arn
              - Effect: Allow
                Action: sts:AssumeRole
                Resource: !Sub arn:aws:iam::*:role/CloudShrinkSatelliteRole
  DiscoveryFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub "${StackName}-discovery"
      Runtime: python3.12
      Handler: app.lambda_handler
      Role: !GetAtt DiscoveryFunctionRole.Arn
      Code:
        S3Bucket: !Ref ArtifactsBucket
        S3Key: !Ref DiscoveryWorkerKey
      Timeout: 900
      Environment:
        Variables:
          VOLUMES_TABLE: !Ref VolumesTable
          SATELLITE_ROLE_NAME: CloudShrinkSatelliteRole
  EvaluationFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: EvaluationPolicies
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:GetItem
                  - dynamodb:PutItem
                  - dynamodb:UpdateItem
                  - dynamodb:DeleteItem
                  - dynamodb:Query
                  - dynamodb:Scan
                  - dynamodb:BatchGetItem
                  - dynamodb:BatchWriteItem
                Resource:
                  - !GetAtt PoliciesTable.Arn
                  - !GetAtt VolumesTable.Arn
  EvaluationFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub "${StackName}-evaluation"
      Runtime: python3.12
      Handler: app.lambda_handler
      Role: !GetAtt EvaluationFunctionRole.Arn
      Code:
        S3Bucket: !Ref ArtifactsBucket
        S3Key: !Ref EvaluationWorkerKey
      Timeout: 300
      Environment:
        Variables:
          POLICIES_TABLE: !Ref PoliciesTable
          VOLUMES_TABLE: !Ref VolumesTable
  StepTriggerFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: TriggerPolicies
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: states:StartExecution
                Resource: !GetAtt ShrinkStateMachine.Arn
  StepTriggerFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub "${StackName}-trigger"
      Runtime: python3.12
      Handler: app.lambda_handler
      Role: !GetAtt StepTriggerFunctionRole.Arn
      Code:
        S3Bucket: !Ref ArtifactsBucket
        S3Key: !Ref StepTriggerKey
      Timeout: 60
      Environment:
        Variables:
          STATE_MACHINE_ARN: !GetAtt ShrinkStateMachine.Arn
  ShrinkStateMachine:
    Type: AWS::StepFunctions::StateMachine
    Properties:
      StateMachineName: !Sub "${StackName}-shrink"
      DefinitionS3Location:
        Bucket: !Ref ArtifactsBucket
        Key: !Ref StateMachineKey
      RoleArn: !GetAtt StateMachineRole.Arn
  StateMachineRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: states.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: CloudShrinkStateMachine
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - ec2:CreateSnapshot
                  - ec2:CreateVolume
                  - ec2:AttachVolume
                  - ec2:DetachVolume
                Resource: '*'
              - Effect: Allow
                Action:
                  - dynamodb:UpdateItem
                Resource: !GetAtt OperationsTable.Arn
              - Effect: Allow
                Action:
                  - dynamodb:UpdateItem
                Resource: !GetAtt VolumesTable.Arn
              - Effect: Allow
                Action:
                  - ssm:SendCommand
                Resource: '*'
Outputs:
  ApiUrl:
    Value: !Sub https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com
  UserPoolId:
    Value: !Ref UserPool
  UserPoolClientId:
    Value: !Ref UserPoolClient
  FrontendBucketName:
    Value: !Ref FrontendBucket
